projectVersion=1.0.0
projectGroup=io.micronaut.el

title=Micronaut Jakarta EL
projectDesc=A Jakarta Expression Language implementation compiled at compilation time
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-jakarta-el
developers=Denis Stepanov

org.gradle.caching=true
org.gradle.jvmargs=-Xmx1g
predictiveTestSelection=false

coreDocsUrl=https://docs.micronaut.io/latest/api/io/micronaut/
guideUrl=https://docs.micronaut.io/latest/guide/

# The Jakarta Expression Language TCK bundle, resolved from the Eclipse download site
elTckBranch=6.0
elTckVersion=6.0.1
