pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.1'
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'jakarta-el-parent'

include 'benchmarks'
include 'jakarta-el'
include 'jakarta-el-annotations'
include 'jakarta-el-bom'
include 'jakarta-el-interpreter'
include 'jakarta-el-interpreter-reflection'
include 'jakarta-el-parser'
include 'jakarta-el-processor'
include 'doc-examples:example-java'
include 'doc-examples:example-groovy'
include 'doc-examples:example-kotlin'
include 'test-suite-custom-annotation'
include 'test-suite-groovy'
include 'test-suite-java'
include 'test-suite-kotlin'
include 'tests:jakarta-el-tck'
include 'tests:jakarta-el-fuzz'

micronautBuild {
    useStandardizedProjectNames.set(true)
    importMicronautCatalog()
    importMicronautCatalog("micronaut-sourcegen")
}
