[versions]
managed-jakarta-el = "6.0.1"

micronaut = "5.1.1"
micronaut-sourcegen = "2.1.0"

junit = "5.11.4"

errorprone-gradle-plugin = "5.1.0"
error_prone_core = "2.49.0"
nullaway = "0.13.8"

[libraries]
# core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

# boms
micronaut-sourcegen = { module = 'io.micronaut.sourcegen:micronaut-sourcegen-bom', version.ref = 'micronaut-sourcegen' }

# managed dependencies
managed-jakarta-el = { module = 'jakarta.el:jakarta.el-api', version.ref = 'managed-jakarta-el' }

# nullability
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
error-prone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "error_prone_core" }

# gradle plugins
gradle-errorprone = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version.ref = "errorprone-gradle-plugin" }

# testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
