plugins {
    id "io.micronaut.build.internal.jakarta-el-module"
}

dependencies {
    api projects.micronautJakartaEl
    api projects.micronautJakartaElParser

    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.jupiter.engine
}
